import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Navbar from './components/Navbar'

const Home: NextPage = () => {
  return (
    <div className="min-h-screen min-w-full dark:bg-secondary flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isMinimized={false} />
      <div className="flex w-full">
        <div className="border-x-red-600 border-8 text-slate-400 mx-auto my-auto">
          <header className="flex-row ">
            <h1 className="text-2xl text-center">Hello World</h1>
            <p className="text-lg">View Players, View Champions, View Builds</p>
          </header>
          <form>

          </form>
        </div>
      </div>

    </div>
  )
}

export default Home
